apiVersion: v1
kind: Pod
metadata:
  name: nginx-namespace
  labels:
    team: ecommerce
    vers: 1.2.9
    environment: production
  annotations:
    desc: web testing 
spec:
  containers:
    - name: nginx
      image: nginx 
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce