apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rep
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort:  80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ExternalName
  externalName: lambda-gibran.com
  selector:
    name: nginx
  ports:
    - port: 80
  