apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication
  labels:
    replica: ecommerce 
  annotations:
    Desc: Replication Testing
spec:
  replicas: 3
  selector:
    app: nginx-rc
  template:
    metadata:
      name: nginx-rc
      labels:
        app: nginx-rc
    spec:
      containers:
        - name: nginx-rep
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: replication-nginx